# Source before starting a new AnythingLLM server. Requires TSUBASA_API_KEY.
export LLM_PROVIDER=generic-openai
export GENERIC_OPEN_AI_BASE_PATH=https://api.tsubasa.sh/v1
export GENERIC_OPEN_AI_API_KEY="${TSUBASA_API_KEY:?Set TSUBASA_API_KEY first}"
export GENERIC_OPEN_AI_MODEL_PREF=tsubasa-pro
export GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT=32768
export GENERIC_OPEN_AI_MAX_TOKENS=4096
export GENERIC_OPEN_AI_MODEL_MAX_TOKEN_KEY=max_tokens
export GENERIC_OPEN_AI_REPORT_USAGE=true
export PROVIDER_DISABLE_NATIVE_TOOL_CALLING="${PROVIDER_DISABLE_NATIVE_TOOL_CALLING:+${PROVIDER_DISABLE_NATIVE_TOOL_CALLING},}generic-openai"
